name: rescue_me
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.3
  phosphor_flutter: ^2.0.1
  neumorphic_ui: ^1.0.1
  flutter_screenutil: ^5.9.0
  phone_numbers_parser: ^8.1.3
  form_validator: ^2.1.1
  flex_color_scheme: ^7.3.1
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  internet_connection_checker: ^1.0.0+1 
  intl_phone_field: ^3.2.0
  open_mail_app: ^0.4.5
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  lottie: ^3.0.0
  password_policy: ^1.2.0
  google_fonts: ^6.1.0
  figma_squircle: ^0.5.3
  cloud_firestore_odm: ^1.0.0-dev.83
  firebase_storage: ^11.6.4
  cloud_firestore: ^4.15.3
  logger: ^1.4.0
  animated_bottom_navigation_bar: ^1.3.3
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  libphonenumber_plugin: ^0.3.3
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  uuid: ^4.3.3
  fluttercontactpicker: ^4.7.0
  flutter_hooks: ^0.20.5
  stacked_themes: ^0.3.12
  battery_plus: ^5.0.3
  geocoding: ^2.2.1+1
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  carousel_slider: ^4.2.1
  bulleted_list: ^0.0.1+0.1a
  super_bullet_list: ^0.0.3
  youtube_player_flutter: ^9.0.0
  flutter_osm_plugin: ^0.70.4

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.1
  stacked_generator:
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  cloud_firestore_odm_generator: ^1.0.0-dev.83

flutter_native_splash:
  color: "#ee9a9a"

  android_12:
    image: assets/splash.png
    icon_background_color: "#ee9a9a"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/